# Generated by Django 3.1.6 on 2022-06-29 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CTList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('forum', models.TextField(default='')),
                ('polls', models.TextField(default='')),
                ('reaction', models.TextField(default='')),
                ('Feedback_ID', models.TextField(default='', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('News_ID', models.TextField(default='', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Guides',
            fields=[
                ('Walkthrough', models.TextField(default='')),
                ('Tips', models.TextField(default='')),
                ('Guide_ID', models.TextField(default='', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('features', models.TextField(default='')),
                ('inclusion', models.TextField(default='')),
                ('Service_ID', models.TextField(default='', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.TextField(default='')),
                ('age', models.IntegerField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('number', models.IntegerField(default='')),
                ('User_ID', models.TextField(default='', primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='form',
        ),
        migrations.AddField(
            model_name='subscription',
            name='usersub',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CTList.user'),
        ),
        migrations.AddField(
            model_name='guides',
            name='serviceguides',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CTList.subscription'),
        ),
        migrations.AddField(
            model_name='feeds',
            name='feedguide',
            field=models.ManyToManyField(to='CTList.Guides'),
        ),
        migrations.AddField(
            model_name='feeds',
            name='feedsfeedback',
            field=models.ManyToManyField(to='CTList.Feedback'),
        ),
        migrations.AddField(
            model_name='feeds',
            name='servicefeeds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CTList.subscription'),
        ),
        migrations.AddField(
            model_name='feeds',
            name='userfeeds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CTList.user'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CTList.user'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='guidefeedback',
            field=models.ManyToManyField(to='CTList.Guides'),
        ),
    ]
