# Generated by Django 3.1.6 on 2022-07-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTList', '0002_auto_20220629_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='question1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='question2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='question3',
            field=models.TextField(default=''),
        ),
    ]
