# Generated by Django 3.1.6 on 2022-07-01 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CTList', '0003_auto_20220701_0357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='question3',
        ),
    ]
