# Generated by Django 3.1.6 on 2022-07-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTList', '0005_remove_feedback_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_ID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
